<?php

/**
 * @file
 * Contains opencalais.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\opencalais\CalaisService;

/**
 * Implements hook_menu().
 */
function opencalais_menu() {
  $items['admin/config/content/opencalais'] = array(
    'title' => 'Open Calais Settings',
    'description' => "Configure Open Calais module.",
    'route_name' => 'opencalais.settings',
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function opencalais_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opencalais module.
    case 'help.page.opencalais':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Utilize the Open Calais API to tag content.') . '</p>';
      return $output;

    default:
  }
}

/*
 * Implements hook_node_update(Drupal Core Entity EntityInterface $node)
 */

function opencalais_node_update($node){
  // Determine if we have any fields that we want to send up
  $my_config = \Drupal::config('opencalais.opencalaisnodeconfig')->get($node->getType());
  $concat_string = '';
  foreach($my_config as $key => $value) {
    // We append a '. ' because we can't depend on users to enter good data
    $concat_string .= strip_tags($node->get($key)->value . '. ');
  }
  ksm($concat_string);
  
  // Send Values.
  if($concat_string != '') {
    $options = array(
      'apiKey' => 'QOFByCaIzW9E0ezjWpOquJfFXAEVNTdm',
      'contentType' => 'text/plain',
      'content' => strip_tags($concat_string),
      'host' => 'api.thomsonreuters.com',
    );
  
    //$calais = opencalais_get_service($options);
    $calais = new CalaisService($options);
    //Get your tags
    $tags = $calais->analyze();
  } 
  ksm($tags); 
}

/**
 * Return the OpenCalais Service class.
 *
 * @param $options An array of option parameters to be sent to the CalaisService class.
 * @return $object The initialized CalaisService object.
 */
function opencalais_get_service($options = array()) {
  return new CalaisService($options);
}
